name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Install 1.16beta
      run: |
        go get golang.org/dl/go1.16beta1
        go1.16beta1 download
        go1.16beta1 version
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get golang.org/dl/go1.16beta1
        go1.16beta1 mod vendor

    - name: Build
      run: |
        go get golang.org/dl/go1.16beta1
        GOOS=darwin CGO_ENABLED=0 go1.16beta1 build -mod=vendor -o builder-darwin -v ./go/builder/main.go
        GOOS=linux CGO_ENABLED=0 go1.16beta1 build -mod=vendor -o builder-darwin -v ./go/builder/main.go

    - name: Test
      run: |
        go get golang.org/dl/go1.16beta1
        go1.16beta1 test -v ./...
